CSV_FILE_PATH = '/Users/Cem/Desktop/5minBTC.csv'

WINDOW_SIZE = 5
DATE_COLUMN = 'Date'
PRICE_COLUMN = 'Close'
RETURN_COLUMN = 'Daily_Return'

LEARNING_RATE = 0.01
N_EPOCHS = 100
HS = 100
BATCH_SIZE = 32

TEST_SPLIT_RATIO = 0.2
VALIDATION_SPLIT_RATIO = 0.1

FEATURE_COLUMNS = ['Open', 'High', 'Low', 'Close', 'Volume']
TARGET_COLUMN = 'Future Volatility'

RF_N_ESTIMATORS = 100
RF_MAX_DEPTH = None
RF_MIN_SAMPLES_SPLIT = 2
RF_MIN_SAMPLES_LEAF = 1

RANDOM_SEED = 42

MODEL_SAVE_PATH = '/Users/Cem/Desktop'

HISTORY_WINDOW = 31

RESULTS_SAVE_PATH = '/Users/Cem/Desktop'
